### ISSUE TITLE
keyError raised when running `bash train.sh`

### ISSUE THREAD

**Issue by ShiqianTan** [FanmengWang/MMPolymer#1]
Dear author,
The Issue is:
When running `bash train.sh`, the error 'anaconda3/envs/MMPolymer/lib/python3.8/site-packages/unicore/trainer.py", line 349, in load_checkpoint
    state["model"], strict=False, model_args=self.args
KeyError: 'model' is raised.

Repeat the error:
I have checked it pretrain.pt by hand using the following code snippet
```python
path = 'ckpt/pretrain.pt'
model = torch.load(path)
model.keys()
```
The key `model` is indeed not in the keys.

Hope you can help me fix the issue.
Thanks.

**Comment by anotherras** [comment]
I'm having the same problem.

**Comment by FanmengWang** [comment]
Hi,
Thank you for being interested in my work
You can fix this problem by reprocessing the current checkpoint, i.e., 
```python 
import torch
path = 'pretrain.pt'
model = torch.load(path)
model_dict = {"model": model}
torch.save(model_dict, 'new_pre.pt')
```
I will also upload the processed checkpoint later.
